
sudo: true
language: php
php:
  - 7.2
  - 7.3

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.3

services:
  - mysql

branches:
  only:
    - /^8.x-1.x/
    - /main/

before_install:
  - export SCRIPT_DIR=$HOME/islandora/.scripts
  - export DRUPAL_DIR=/opt/drupal
  - export COMPOSER_PATH="/home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer"

install:
  - git clone https://github.com/Islandora/documentation.git $HOME/islandora

before_script:
  - $SCRIPT_DIR/travis_setup_drupal.sh
  - git -C "$TRAVIS_BUILD_DIR" checkout -b travis-testing
  - cd $DRUPAL_DIR;
  - chmod -R u+w web/sites/default
  - php -dmemory_limit=-1 $COMPOSER_PATH config repositories.local path "$TRAVIS_BUILD_DIR"
  - php -dmemory_limit=-1 $COMPOSER_PATH require "islandora/jsonld:dev-travis-testing as dev-8.x-1.x" --prefer-source
  - cd web; drush en -y jsonld
  
script:
  - $SCRIPT_DIR/travis_scripts.sh
  - $SCRIPT_DIR/run-tests.sh "jsonld"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: $SLACK_NOTIFICATION_KEY
