
sudo: true
language: php
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
    fast_finish: true

branches:
  only:
    - /^8.x/

before_install:
  - export SCRIPT_DIR=$HOME/CLAW/.scripts
  - export DRUPAL_DIR=/opt/drupal

install:
  - git clone https://github.com/Islandora-CLAW/CLAW.git $HOME/CLAW
  - $SCRIPT_DIR/travis_setup_drupal.sh
  - git -C "$TRAVIS_BUILD_DIR" checkout -b travis-testing
  - cd $DRUPAL_DIR; composer config repositories.local path "$TRAVIS_BUILD_DIR"
  - composer require "islandora/jsonld:dev-travis-testing as dev-8.x-1.x" --prefer-source
  - cd web; drush en -y jsonld

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - phpcs --standard=Drupal --ignore=*.md --extensions=php,module,inc,install,test,profile,theme,css,info $TRAVIS_BUILD_DIR
  - phpcpd --names *.module,*.inc,*.test,*.php $TRAVIS_BUILD_DIR
  #- php core/scripts/run-tests.sh --verbose --php `which php` jsonld

notifications:
  irc:
    channels:
      - "irc.freenode.org#islandora"
    on_success: change
    on_failure: always
    skip_join: true
